version: "3.9"
services:
  flask_service:
    container_name: flask_service_container
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - ${PATH_ROOT_COMPLETED_FILES}:${PATH_DOCKER_COMPLETED_FILES}
      - ${PATH_ROOT}:${PATH_DOCKER}
      - ${PATH_DOCUMENTS}:${PATH_DOCKER_DOCUMENTS}
    environment:
      PATH_ROOT_COMPLETED_FILES: ${PATH_DOCKER_COMPLETED_FILES}
      PATH_ROOT: ${PATH_DOCKER}
      PATH_DOCUMENTS: ${PATH_DOCKER_DOCUMENTS}
    build:
      context: ./
      dockerfile: ./Dockerfile
    command:
      bash -c "python3 main.py"

  unified_data:
    container_name: unified_data
    image: python:3.8
    restart: always
    ports:
      - "5005:5005"
    build:
      context: unified
      dockerfile: ./Dockerfile
    command:
      bash -c "python3 split_scanned_by_paragraph.py"